Controllers/LogRegController.cs
using Microsoft.EntityFrameworkCore;
using Exam.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
// Other usings

public class LogRegController : Controller
{
    private ExamContext dbContext;
 
    public LogRegController(ExamContext context)
    {
        dbContext = context;
    }

//------------------------------------------LOGIN PAGE --------------------------------------
    [HttpGet]
    [Route("/")]
    public IActionResult Log()
    {
        return View("index");
    }

//---------------------------------LOG OUT -----------------------------------------------------
    [HttpGet]
    [Route("logout")]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Log");
    }


//-----------------------------------------LOGIN LOGIC ------------------------------------------
    [HttpPost]
    [Route("login")]
    public IActionResult Login(LoginUser userSubmission)
    {
        if(ModelState.IsValid)
        {
            var userInDb = dbContext.Users.FirstOrDefault(u => u.Email == userSubmission.LoginEmail);
            if(userInDb == null)
            {
                ModelState.AddModelError("LoginPassword", "Invalid Email/Password");
                return View("index");
            }

            var hasher = new PasswordHasher<LoginUser>();            
            var result = hasher.VerifyHashedPassword(userSubmission, userInDb.Password, userSubmission.LoginPassword);            
            if(result == 0)
            {
                ModelState.AddModelError("LoginPassword", "Invalid Email/Password");                    
                return View("index");
            }
            
            var userInfo = dbContext.Users.FirstOrDefault(u => u.Email == userSubmission.LoginEmail);
            HttpContext.Session.SetInt32("UserId", userInfo.UserId);
            HttpContext.Session.SetString("UserName", userInfo.FirstName);        
            return Redirect("home");
        }

        else
        {
            return View("index");
        }
    }

//-----------------------------------REGISTRATION LOGIC -------------------------------------------
    [HttpPost]
    [Route("register")]
    public IActionResult Register(User user)
    {
        if(ModelState.IsValid)
        {
            if(dbContext.Users.Any(u => u.Email == user.Email))
            {
                ModelState.AddModelError("Email", "Email already in use!");
                return View("index");
            }
            PasswordHasher<User> Hasher = new PasswordHasher<User>();
            user.Password = Hasher.HashPassword(user, user.Password);
            dbContext.Add(user);
            dbContext.SaveChanges();

            HttpContext.Session.SetInt32("UserId", user.UserId);
            HttpContext.Session.SetString("UserName", user.FirstName);
            return Redirect("home");
        }
        else
        {
            return View("index");
        }
    }
}

Views/LogReg/index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
<!-- -------------------------------------- BOOTSTRAP AND CSS LINKS----------------------------------- -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/style.css" />
<!-- ------------------------------------------------------------------------------------------------- -->
</head>
<body>
    <div class="container">
        <div class="forms">
            <partial name="register"/>
        </div>
        <div class="forms">
            <partial name="login"/>
        </div>
    </div>
</body>
</html>

Views/LogReg/login.cshtml
@model LoginUser     
<form asp-action="login" asp-controller="LogReg" method="POST">
    <h3>Login here!</h3>
    <div class="form-group">
        <label asp-for="LoginEmail"></label>
        <input asp-for="LoginEmail" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="LoginEmail" class="alert-danger" role="alert"></span>
    </div>
    <div class="form-group">
        <label asp-for="LoginPassword"></label>
        <input asp-for="LoginPassword" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="LoginPassword" class="alert-danger" role="alert"></span>
    </div>
    <button type="submit" class="btn btn-success">Login</button>
</form>

Views/LogReg/register.cshtml
@model User
<form asp-action="Register" class="form-horizontal" asp-controller="LogReg" method="POST">
    <h3>Register here!</h3>
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="FirstName" class="alert-danger" role="alert"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="LastName" class="alert-danger" role="alert"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="Email" class="alert-danger" role="alert"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="Password" class="alert-danger" role="alert"></span>
    </div>
    <div class="form-group">
        <label asp-for="Confirm"></label>
        <input asp-for="Confirm" class="form-control col-md-6" aria-describedby="emailHelp">
        <span asp-validation-for="Confirm" class="alert-danger" role="alert"></span>
    </div>
    <button type="submit" class="btn btn-success">Register</button>
</form>